<?xml version="1.0" encoding="utf-8"?><Database Name="fcgl" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=fcgl;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="fcglConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.address" Member="address">
    <Type Name="address">
      <Column Name="address_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="area" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="community" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="address_house" Member="house" ThisKey="address_id" OtherKey="address" Type="house" />
    </Type>
  </Table>
  <Table Name="dbo.setting" Member="setting">
    <Type Name="setting">
      <Column Name="renthouse" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rentsetting" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="renthouse_setting" Member="renthouse1" ThisKey="renthouse" OtherKey="house_id" Type="renthouse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.agent" Member="agent">
    <Type Name="agent">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="profession" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="register_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="valid_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="trade_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="agent_delegate" Member="delegate" ThisKey="person_id" OtherKey="agent" Type="delegate" />
      <Association Name="agent_manage" Member="manage" ThisKey="person_id" OtherKey="agent" Type="manage" />
      <Association Name="person_agent" Member="person" ThisKey="person_id" OtherKey="person_id" Type="person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.delegate" Member="delegate">
    <Type Name="delegate">
      <Column Name="member" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="agent" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="house" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="messages" Type="System.String" DbType="VarChar(140)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="agent_delegate" Member="agent1" ThisKey="agent" OtherKey="person_id" Type="agent" IsForeignKey="true" />
      <Association Name="house_delegate" Member="house1" ThisKey="house" OtherKey="house_id" Type="house" IsForeignKey="true" />
      <Association Name="member_delegate" Member="member1" ThisKey="member" OtherKey="person_id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.house" Member="house">
    <Type Name="house">
      <Column Name="house_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="levels" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="area" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="orientation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="types" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="decoration" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="thumbnails" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="room" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="hall" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="toilet" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="address" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="member" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="house_delegate" Member="delegate" ThisKey="house_id" OtherKey="house" Type="delegate" />
      <Association Name="house_manage" Member="manage" ThisKey="house_id" OtherKey="house" Type="manage" />
      <Association Name="house_photo" Member="photo" ThisKey="house_id" OtherKey="house" Type="photo" />
      <Association Name="house_renthouse" Member="renthouse" ThisKey="house_id" OtherKey="house_id" Type="renthouse" Cardinality="One" />
      <Association Name="house_salehouse" Member="salehouse" ThisKey="house_id" OtherKey="house_id" Type="salehouse" Cardinality="One" />
      <Association Name="address_house" Member="address1" ThisKey="address" OtherKey="address_id" Type="address" IsForeignKey="true" />
      <Association Name="member_house" Member="member1" ThisKey="member" OtherKey="person_id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.manage" Member="manage">
    <Type Name="manage">
      <Column Name="house" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="agent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="agent_manage" Member="agent1" ThisKey="agent" OtherKey="person_id" Type="agent" IsForeignKey="true" />
      <Association Name="house_manage" Member="house1" ThisKey="house" OtherKey="house_id" Type="house" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="member">
    <Type Name="member">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="identity_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="member_delegate" Member="delegate" ThisKey="person_id" OtherKey="member" Type="delegate" />
      <Association Name="member_house" Member="house" ThisKey="person_id" OtherKey="member" Type="house" />
      <Association Name="person_member" Member="person" ThisKey="person_id" OtherKey="person_id" Type="person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.person" Member="person">
    <Type Name="person">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="names" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="person_agent" Member="agent" ThisKey="person_id" OtherKey="person_id" Type="agent" Cardinality="One" />
      <Association Name="person_member" Member="member" ThisKey="person_id" OtherKey="person_id" Type="member" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.photo" Member="photo">
    <Type Name="photo">
      <Column Name="house" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="picture" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="house_photo" Member="house1" ThisKey="house" OtherKey="house_id" Type="house" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.renthouse" Member="renthouse">
    <Type Name="renthouse">
      <Column Name="house_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="types" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="payment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="renthouse_setting" Member="setting" ThisKey="house_id" OtherKey="renthouse" Type="setting" />
      <Association Name="house_renthouse" Member="house" ThisKey="house_id" OtherKey="house_id" Type="house" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.salehouse" Member="salehouse">
    <Type Name="salehouse">
      <Column Name="house_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="types" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="developer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="property_costs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="build_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="house_salehouse" Member="house" ThisKey="house_id" OtherKey="house_id" Type="house" IsForeignKey="true" />
    </Type>
  </Table>
</Database>